versions:
  "3.1.3-audacity":
    folder: "3.1.3"
  "3.1.3.1-audacity":
    folder: "3.1.3"
  "3.1.3.2-audacity":
    folder: "3.1.3"
  "3.1.3.3-audacity":
    folder: "3.1.3"
  "3.1.3.4-audacity":
    folder: "3.1.3"
  "3.1.3.5-audacity":
    folder: "3.1.3"
  "3.1.3.6-audacity":
    folder: "3.1.3"
